site_name: ""
# repo_url: https://github.com/fzinfz/book

theme:
    name: mkdocs
    custom_dir: custom_theme/

markdown_extensions:
    toc:
        permalink: true
    pymdownx.magiclink:

plugins:
  - search
  - exclude:
      glob:
        - SUMMARY.md
      regex:
        - '.*\.(sh|txt)$'

# https://oprypin.github.io/mkdocs-literate-nav/reference.html
# not working ?
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true