site_name: Ferro's Notes
# theme: readthedocs
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shortener: true
plugins:
  - exclude:
      glob:
        - SUMMARY.md
      regex:
        - '.*\.(tmp|txt)$'
        - '^[.]'
